### ISSUE TITLE
CF Workers: Unpredictable behavior when dynamically storing `template` in memory

### ISSUE THREAD

**Issue by potatopotaro** [ryansolid/solid-start#3]
The `template` variable within [entry-stream.js](https://github.com/ryansolid/solid-start/blob/7a858becb9ebd7515b49fabc3b1e08d001d81be8/packages/start-cloudflare-workers/entry-async.js#L15) can be stale, which will lead to very odd behavior upon uploading changes to CF Workers KV (while an instance of `template` is instantiated).

```
// solid-start-cloudflare-workers/entry-stream.js
// ...
let template;
// ...
async function handleEvent(event) {
    // ...
    if (!template) { // <=== Can be stale if worker's template is updated AND already in memory
      template = await __STATIC_CONTENT.list({prefix: "index"})
        .then(res => __STATIC_CONTENT.get(res.keys[0].name));
    }
    // ...
}
```
An easy repro is:
1. Successfully create and run a fresh `solid-start` + CF worker project with `wrangler dev`.
2. Add a single character to the end of your `title` in the `index.html` vite entry (for example, "!").
3. Build your project once again, follow it with `wrangler dev`.
4. Notice the large body of text (stringified JS script) that is returned + strange network requests.

**Comment by potatopotaro** [comment]
While this is unfortunate, I believe there's an opportunity to pre-define the `template` variable as a constant/import; shaving a few milliseconds off TTFB, since we won't have to fetch the initial `template` value from KV.

**Comment by ryansolid** [comment]
Yeah I think I can do this better. I did this because I was having issue with Vite originally. And I just ported from my HN demo. I think better just bundle the template into the JS code.
